M48
; DRILL file {KiCad 7.0.6} date Thu Nov 30 23:32:06 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-30T23:32:06-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X124.84Y-120.09
X129.92Y-120.09
T2
X75.43Y-73.54
X75.43Y-78.14
X75.43Y-82.74
T3
X127.38Y-112.47
T0
M30
